"""
tests/test_mtls.py

Tests for nexus_a2a/security/mtls.py — MutualTLS.

Coverage:
  - MutualTLSConfig: construction, validate(), from_env()
  - MtlsConfigError: missing cert, key, CA, unreadable files
  - build_client_ssl_context(): returns ssl.SSLContext with correct settings
  - build_server_ssl_context(): returns ssl.SSLContext, verify_client flag
  - verify_peer_certificate(): parses DER cert into CertInfo
  - CertInfo: fields, __str__, is_expired, days_remaining
  - _parse_cert_dict(): subject/issuer/SAN extraction
  - from_env(): reads NEXUS_MTLS_* variables, base64 PEM bytes
  - In-memory PEM bytes (cert_pem/key_pem/ca_pem) paths

All tests use real certs generated by the conftest fixture — no mocking
of the ssl module, so we test the actual Python ssl integration.
"""

from __future__ import annotations

import base64
import os
import ssl
import subprocess
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from unittest.mock import patch

import pytest

from nexus_a2a.security.mtls import (
    CertInfo,
    MtlsCertificateError,
    MtlsConfigError,
    MtlsError,
    MutualTLSConfig,
    _parse_cert_dict,
    build_client_ssl_context,
    build_server_ssl_context,
    verify_peer_certificate,
)


# ── Test fixtures (real certs via openssl) ───────────────────────────────────

@pytest.fixture(scope="session")
def cert_dir(tmp_path_factory) -> Path:
    """Generate a CA + agent cert pair for the entire test session."""
    d = tmp_path_factory.mktemp("certs")

    def run(cmd: str) -> None:
        result = subprocess.run(
            cmd, shell=True, capture_output=True, text=True, cwd=str(d)
        )
        assert result.returncode == 0, (
            f"openssl command failed:\n{cmd}\nstderr: {result.stderr}"
        )

    # CA
    run("openssl genrsa -out ca.key 2048")
    run(
        'openssl req -new -x509 -days 3650 -key ca.key -out ca.crt '
        '-subj "/C=US/O=NexusTestCA/CN=NexusTestCA"'
    )
    # Agent cert signed by CA
    run("openssl genrsa -out agent.key 2048")
    run(
        'openssl req -new -key agent.key -out agent.csr '
        '-subj "/C=US/O=NexusTest/CN=agent-a"'
    )
    run(
        "openssl x509 -req -days 3650 -in agent.csr "
        "-CA ca.crt -CAkey ca.key -CAcreateserial -out agent.crt"
    )
    # Expired cert (backdated) — skip on OpenSSL 3.x which dropped -startdate/-enddate.
    # Tests for expiry logic use mocked CertInfo directly instead.
    try:
        run("openssl genrsa -out expired.key 2048")
        run(
            'openssl req -new -key expired.key -out expired.csr '
            '-subj "/C=US/O=NexusTest/CN=expired-agent"'
        )
        run(
            "openssl x509 -req -days 1 "
            "-startdate 20200101000000Z -enddate 20200102000000Z "
            "-in expired.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out expired.crt"
        )
    except AssertionError:
        # OpenSSL 3.x dropped -startdate/-enddate; expired cert tests use mocks
        pass
    return d


@pytest.fixture
def valid_config(cert_dir: Path) -> MutualTLSConfig:
    return MutualTLSConfig(
        cert_file=cert_dir / "agent.crt",
        key_file=cert_dir  / "agent.key",
        ca_file=cert_dir   / "ca.crt",
    )


@pytest.fixture
def pem_config(cert_dir: Path) -> MutualTLSConfig:
    """Config using in-memory PEM bytes instead of file paths."""
    return MutualTLSConfig(
        cert_pem=(cert_dir / "agent.crt").read_bytes(),
        key_pem=(cert_dir  / "agent.key").read_bytes(),
        ca_pem=(cert_dir   / "ca.crt").read_bytes(),
    )


# ── Exception hierarchy ───────────────────────────────────────────────────────

class TestExceptions:

    def test_mtls_config_error_is_mtls_error(self):
        exc = MtlsConfigError("bad config")
        assert isinstance(exc, MtlsError)

    def test_mtls_cert_error_is_mtls_error(self):
        exc = MtlsCertificateError("bad cert")
        assert isinstance(exc, MtlsError)

    def test_config_error_includes_field(self):
        exc = MtlsConfigError("bad value", field="cert_file")
        assert "cert_file" in str(exc)

    def test_config_error_without_field(self):
        exc = MtlsConfigError("bad value")
        assert "bad value" in str(exc)

    def test_cert_error_includes_subject(self):
        exc = MtlsCertificateError("expired", subject="CN=agent-a")
        assert "agent-a" in str(exc)

    def test_cert_error_without_subject(self):
        exc = MtlsCertificateError("invalid")
        assert "invalid" in str(exc)


# ── CertInfo ──────────────────────────────────────────────────────────────────

class TestCertInfo:

    def test_str_not_expired(self):
        info = CertInfo(
            subject="CN=agent-a",
            issuer="CN=CA",
            not_before=datetime(2024, 1, 1, tzinfo=timezone.utc),
            not_after=datetime(2035, 1, 1, tzinfo=timezone.utc),
            serial="ABCD",
            days_remaining=100,
            is_expired=False,
        )
        s = str(info)
        assert "agent-a" in s
        assert "100d remaining" in s

    def test_str_expired(self):
        info = CertInfo(
            subject="CN=old-agent",
            issuer="CN=CA",
            not_before=datetime(2020, 1, 1, tzinfo=timezone.utc),
            not_after=datetime(2020, 1, 2, tzinfo=timezone.utc),
            serial="0001",
            days_remaining=-100,
            is_expired=True,
        )
        assert "EXPIRED" in str(info)

    def test_san_default_empty(self):
        info = CertInfo(
            subject="CN=a",
            issuer="CN=ca",
            not_before=datetime.now(timezone.utc),
            not_after=datetime.now(timezone.utc),
            serial="01",
        )
        assert info.san == []


# ── MutualTLSConfig.validate() ────────────────────────────────────────────────

class TestMutualTLSConfigValidate:

    def test_valid_file_config_passes(self, valid_config):
        valid_config.validate()  # should not raise

    def test_valid_pem_config_passes(self, pem_config):
        pem_config.validate()  # should not raise

    def test_missing_cert_raises(self, cert_dir):
        cfg = MutualTLSConfig(
            key_file=cert_dir / "agent.key",
            ca_file=cert_dir  / "ca.crt",
        )
        with pytest.raises(MtlsConfigError, match="cert"):
            cfg.validate()

    def test_missing_key_raises(self, cert_dir):
        cfg = MutualTLSConfig(
            cert_file=cert_dir / "agent.crt",
            ca_file=cert_dir   / "ca.crt",
        )
        with pytest.raises(MtlsConfigError, match="key"):
            cfg.validate()

    def test_missing_ca_with_verify_client_raises(self, cert_dir):
        cfg = MutualTLSConfig(
            cert_file=cert_dir / "agent.crt",
            key_file=cert_dir  / "agent.key",
            verify_client=True,
        )
        with pytest.raises(MtlsConfigError, match="CA"):
            cfg.validate()

    def test_missing_ca_without_verify_client_passes(self, cert_dir):
        cfg = MutualTLSConfig(
            cert_file=cert_dir / "agent.crt",
            key_file=cert_dir  / "agent.key",
            verify_client=False,
        )
        cfg.validate()  # should not raise — no CA needed when not verifying clients

    def test_nonexistent_cert_file_raises(self, cert_dir):
        cfg = MutualTLSConfig(
            cert_file=cert_dir / "nope.crt",
            key_file=cert_dir  / "agent.key",
            ca_file=cert_dir   / "ca.crt",
        )
        with pytest.raises(MtlsConfigError, match="not found"):
            cfg.validate()

    def test_nonexistent_key_file_raises(self, cert_dir):
        cfg = MutualTLSConfig(
            cert_file=cert_dir / "agent.crt",
            key_file=cert_dir  / "nope.key",
            ca_file=cert_dir   / "ca.crt",
        )
        with pytest.raises(MtlsConfigError, match="not found"):
            cfg.validate()

    def test_nonexistent_ca_file_raises(self, cert_dir):
        cfg = MutualTLSConfig(
            cert_file=cert_dir / "agent.crt",
            key_file=cert_dir  / "agent.key",
            ca_file=cert_dir   / "nope.crt",
        )
        with pytest.raises(MtlsConfigError, match="not found"):
            cfg.validate()

    def test_pem_bytes_override_missing_files(self, cert_dir):
        """If PEM bytes are provided, missing file is irrelevant."""
        cfg = MutualTLSConfig(
            cert_pem=(cert_dir / "agent.crt").read_bytes(),
            key_pem=(cert_dir  / "agent.key").read_bytes(),
            ca_pem=(cert_dir   / "ca.crt").read_bytes(),
            cert_file=None,   # no file needed
        )
        cfg.validate()  # should not raise


# ── MutualTLSConfig._effective_*() ───────────────────────────────────────────

class TestEffectiveMethods:

    def test_effective_cert_returns_file_bytes(self, cert_dir):
        cfg = MutualTLSConfig(cert_file=cert_dir / "agent.crt")
        data = cfg._effective_cert()
        assert data is not None
        assert b"CERTIFICATE" in data

    def test_effective_cert_returns_pem_bytes_if_set(self, cert_dir):
        pem = b"FAKE_PEM_BYTES"
        cfg = MutualTLSConfig(cert_pem=pem, cert_file=cert_dir / "agent.crt")
        assert cfg._effective_cert() == pem  # in-memory wins

    def test_effective_key_returns_file_bytes(self, cert_dir):
        cfg = MutualTLSConfig(key_file=cert_dir / "agent.key")
        data = cfg._effective_key()
        assert data is not None
        assert b"PRIVATE KEY" in data

    def test_effective_key_returns_pem_bytes_if_set(self, cert_dir):
        pem = b"FAKE_KEY_BYTES"
        cfg = MutualTLSConfig(key_pem=pem, key_file=cert_dir / "agent.key")
        assert cfg._effective_key() == pem

    def test_effective_ca_returns_file_bytes(self, cert_dir):
        cfg = MutualTLSConfig(ca_file=cert_dir / "ca.crt")
        data = cfg._effective_ca()
        assert data is not None
        assert b"CERTIFICATE" in data

    def test_effective_ca_returns_none_when_not_set(self):
        cfg = MutualTLSConfig()
        assert cfg._effective_ca() is None

    def test_effective_ca_pem_wins_over_file(self, cert_dir):
        pem = b"FAKE_CA"
        cfg = MutualTLSConfig(ca_pem=pem, ca_file=cert_dir / "ca.crt")
        assert cfg._effective_ca() == pem


# ── build_client_ssl_context() ────────────────────────────────────────────────

class TestBuildClientSslContext:

    def test_returns_ssl_context(self, valid_config):
        ctx = build_client_ssl_context(valid_config)
        assert isinstance(ctx, ssl.SSLContext)

    def test_context_has_correct_protocol(self, valid_config):
        ctx = build_client_ssl_context(valid_config)
        # Should be a client-side TLS context
        assert ctx.verify_mode == ssl.CERT_REQUIRED

    def test_verify_hostname_true_by_default(self, valid_config):
        ctx = build_client_ssl_context(valid_config)
        assert ctx.check_hostname is True

    def test_verify_hostname_false_when_disabled(self, cert_dir):
        cfg = MutualTLSConfig(
            cert_file=cert_dir / "agent.crt",
            key_file=cert_dir  / "agent.key",
            ca_file=cert_dir   / "ca.crt",
            verify_hostname=False,
        )
        ctx = build_client_ssl_context(cfg)
        assert ctx.check_hostname is False

    def test_pem_config_builds_context(self, pem_config):
        ctx = build_client_ssl_context(pem_config)
        assert isinstance(ctx, ssl.SSLContext)

    def test_raises_config_error_without_cert(self, cert_dir):
        cfg = MutualTLSConfig(
            key_file=cert_dir / "agent.key",
            ca_file=cert_dir  / "ca.crt",
        )
        with pytest.raises(MtlsConfigError):
            build_client_ssl_context(cfg)

    def test_no_ca_uses_system_defaults(self, cert_dir):
        """verify_client=False + no CA should still build a context."""
        cfg = MutualTLSConfig(
            cert_file=cert_dir / "agent.crt",
            key_file=cert_dir  / "agent.key",
            verify_client=False,
            verify_hostname=False,
        )
        ctx = build_client_ssl_context(cfg)
        assert isinstance(ctx, ssl.SSLContext)

    def test_minimum_tls_version_applied(self, valid_config):
        valid_config.min_tls_version = ssl.TLSVersion.TLSv1_2
        ctx = build_client_ssl_context(valid_config)
        assert ctx.minimum_version == ssl.TLSVersion.TLSv1_2


# ── build_server_ssl_context() ────────────────────────────────────────────────

class TestBuildServerSslContext:

    def test_returns_ssl_context(self, valid_config):
        ctx = build_server_ssl_context(valid_config)
        assert isinstance(ctx, ssl.SSLContext)

    def test_verify_client_true_requires_cert(self, valid_config):
        ctx = build_server_ssl_context(valid_config)
        assert ctx.verify_mode == ssl.CERT_REQUIRED

    def test_verify_client_false_no_cert_required(self, cert_dir):
        cfg = MutualTLSConfig(
            cert_file=cert_dir / "agent.crt",
            key_file=cert_dir  / "agent.key",
            verify_client=False,
        )
        ctx = build_server_ssl_context(cfg)
        assert ctx.verify_mode == ssl.CERT_NONE

    def test_pem_config_builds_server_context(self, pem_config):
        ctx = build_server_ssl_context(pem_config)
        assert isinstance(ctx, ssl.SSLContext)

    def test_raises_config_error_without_key(self, cert_dir):
        cfg = MutualTLSConfig(
            cert_file=cert_dir / "agent.crt",
            ca_file=cert_dir   / "ca.crt",
        )
        with pytest.raises(MtlsConfigError):
            build_server_ssl_context(cfg)

    def test_minimum_tls_version_applied(self, valid_config):
        valid_config.min_tls_version = ssl.TLSVersion.TLSv1_2
        ctx = build_server_ssl_context(valid_config)
        assert ctx.minimum_version == ssl.TLSVersion.TLSv1_2


# ── from_env() ────────────────────────────────────────────────────────────────

class TestFromEnv:

    def test_reads_file_paths_from_env(self, cert_dir):
        env = {
            "NEXUS_MTLS_CERT_FILE": str(cert_dir / "agent.crt"),
            "NEXUS_MTLS_KEY_FILE":  str(cert_dir / "agent.key"),
            "NEXUS_MTLS_CA_FILE":   str(cert_dir / "ca.crt"),
        }
        with patch.dict(os.environ, env, clear=False):
            cfg = MutualTLSConfig.from_env()
        assert str(cfg.cert_file) == str(cert_dir / "agent.crt")
        assert str(cfg.key_file)  == str(cert_dir / "agent.key")
        assert str(cfg.ca_file)   == str(cert_dir / "ca.crt")

    def test_reads_pem_bytes_from_env(self, cert_dir):
        cert_b64 = base64.b64encode((cert_dir / "agent.crt").read_bytes()).decode()
        key_b64  = base64.b64encode((cert_dir / "agent.key").read_bytes()).decode()
        ca_b64   = base64.b64encode((cert_dir / "ca.crt").read_bytes()).decode()
        env = {
            "NEXUS_MTLS_CERT_PEM": cert_b64,
            "NEXUS_MTLS_KEY_PEM":  key_b64,
            "NEXUS_MTLS_CA_PEM":   ca_b64,
        }
        with patch.dict(os.environ, env, clear=False):
            cfg = MutualTLSConfig.from_env()
        assert cfg.cert_pem is not None
        assert b"CERTIFICATE" in cfg.cert_pem

    def test_verify_client_true_from_env(self):
        with patch.dict(os.environ, {"NEXUS_MTLS_VERIFY_CLIENT": "true"}):
            cfg = MutualTLSConfig.from_env()
        assert cfg.verify_client is True

    def test_verify_client_false_from_env(self):
        with patch.dict(os.environ, {"NEXUS_MTLS_VERIFY_CLIENT": "false"}):
            cfg = MutualTLSConfig.from_env()
        assert cfg.verify_client is False

    def test_verify_hostname_false_from_env(self):
        with patch.dict(os.environ, {"NEXUS_MTLS_VERIFY_HOSTNAME": "0"}):
            cfg = MutualTLSConfig.from_env()
        assert cfg.verify_hostname is False

    def test_invalid_base64_raises_config_error(self):
        with patch.dict(os.environ, {"NEXUS_MTLS_CERT_PEM": "!!!not-base64!!!"}):
            with pytest.raises(MtlsConfigError, match="base64"):
                MutualTLSConfig.from_env()

    def test_empty_env_returns_empty_config(self):
        clean = {k: v for k, v in os.environ.items() if not k.startswith("NEXUS_MTLS")}
        with patch.dict(os.environ, clean, clear=True):
            cfg = MutualTLSConfig.from_env()
        assert cfg.cert_file is None
        assert cfg.cert_pem is None


# ── _parse_cert_dict() ────────────────────────────────────────────────────────

class TestParseCertDict:

    def test_parses_subject(self):
        cert_dict = {
            "subject": ((("commonName", "agent-a"),), (("organizationName", "NexusTest"),)),
            "issuer":  ((("commonName", "NexusTestCA"),),),
            "subjectAltName": (),
        }
        subject, issuer, san = _parse_cert_dict(cert_dict)
        assert "agent-a" in subject
        assert "NexusTest" in subject

    def test_parses_issuer(self):
        cert_dict = {
            "subject": ((("commonName", "agent-a"),),),
            "issuer":  ((("commonName", "MyCA"),),),
            "subjectAltName": (),
        }
        _, issuer, _ = _parse_cert_dict(cert_dict)
        assert "MyCA" in issuer

    def test_parses_san(self):
        cert_dict = {
            "subject": ((("commonName", "agent-a"),),),
            "issuer":  ((("commonName", "CA"),),),
            "subjectAltName": (
                ("DNS", "agent-a.nexus.local"),
                ("IP Address", "10.0.0.1"),
            ),
        }
        _, _, san = _parse_cert_dict(cert_dict)
        assert any("agent-a.nexus.local" in s for s in san)
        assert any("10.0.0.1" in s for s in san)

    def test_empty_cert_dict_returns_empty_strings(self):
        subject, issuer, san = _parse_cert_dict({})
        assert subject == ""
        assert issuer  == ""
        assert san     == []

    def test_empty_san_returns_empty_list(self):
        cert_dict = {
            "subject": ((("commonName", "a"),),),
            "issuer":  ((("commonName", "ca"),),),
            "subjectAltName": (),
        }
        _, _, san = _parse_cert_dict(cert_dict)
        assert san == []


# ── Integration: build context + verify peer ──────────────────────────────────

class TestIntegration:

    def test_client_and_server_contexts_are_distinct(self, valid_config):
        client_ctx = build_client_ssl_context(valid_config)
        server_ctx = build_server_ssl_context(valid_config)
        # Different protocol directions
        assert client_ctx is not server_ctx

    def test_check_expiry_days_zero_skips_warning(self, cert_dir, caplog):
        cfg = MutualTLSConfig(
            cert_file=cert_dir / "agent.crt",
            key_file=cert_dir  / "agent.key",
            ca_file=cert_dir   / "ca.crt",
            check_expiry_days=0,
        )
        import logging
        with caplog.at_level(logging.WARNING, logger="nexus_a2a.security.mtls"):
            build_client_ssl_context(cfg)
        assert not any("expires" in r.message for r in caplog.records)

    def test_verify_peer_certificate_returns_cert_info(self, cert_dir, valid_config):
        """verify_peer_certificate() should return a CertInfo without raising."""
        cert_der = ssl.PEM_cert_to_DER_cert(
            (cert_dir / "agent.crt").read_text()
        )
        info = verify_peer_certificate(valid_config, cert_der)
        assert isinstance(info, CertInfo)

    def test_verify_peer_certificate_invalid_der_raises(self, valid_config):
        with pytest.raises(MtlsCertificateError):
            verify_peer_certificate(valid_config, b"not-a-real-cert")

    def test_mtls_config_defaults(self):
        cfg = MutualTLSConfig()
        assert cfg.verify_client is True
        assert cfg.verify_hostname is True
        assert cfg.min_tls_version == ssl.TLSVersion.TLSv1_2
        assert cfg.ciphers is None
        assert cfg.check_expiry_days == 30